# Generated by Django 4.1 on 2022-08-08 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
